"""
preview_scenes.py — Generate WebP thumbnails from user-supplied scene PNGs.

Walks the saves tree.  For each `.laops` file that has a matching `.png`
preview (same stem) and no fresh `.webp` yet:

    1. Opens the PNG with Pillow.
    2. Resizes to fit within 320×240 (or --size WxH), preserving aspect
       ratio, using Image.LANCZOS.
    3. Saves as `.webp` alongside the `.laops` and `.png` files.

A `.webp` that is already newer than its `.png` is skipped unless --force
is given.  The source `.png` is never deleted — it stays in place as the
source of truth.  Only the `.webp` is consumed by post_catalog.py.

Preview image convention — the PNG must share the .laops stem:

    saves/Combat/cs_office.laops
    saves/Combat/cs_office.json
    saves/Combat/cs_office.png    ← large source screenshot (e.g. 1024×1024)
    saves/Combat/cs_office.webp   ← generated by this script

Usage:
    python scripts/preview_scenes.py --saves saves
    python scripts/preview_scenes.py --saves saves --size 320x240 --force

Dependencies:
    pip install Pillow
"""

import argparse
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("ERROR: missing dependency: Pillow\n  pip install Pillow")


def parse_size(value: str) -> tuple[int, int]:
    w, sep, h = value.lower().partition("x")
    if not sep:
        sys.exit(f"ERROR: --size must be WxH, got: {value!r}")
    try:
        width, height = int(w), int(h)
    except ValueError:
        sys.exit(f"ERROR: --size must be WxH numbers, got: {value!r}")
    if width <= 0 or height <= 0:
        sys.exit(f"ERROR: --size dimensions must be positive, got: {value!r}")
    return width, height


def render_folder(
    folder: Path,
    size: tuple[int, int],
    force: bool,
    stats: dict,
    errors: list,
) -> None:
    for laops in sorted(folder.glob("*.laops"), key=lambda p: p.name.lower()):
        png  = laops.with_suffix(".png")
        webp = laops.with_suffix(".webp")

        if not png.exists():
            stats["no_png"] += 1
            continue

        if not force and webp.exists() and webp.stat().st_mtime >= png.stat().st_mtime:
            stats["skipped"] += 1
            continue

        try:
            img = Image.open(str(png))
            img.thumbnail(size, Image.LANCZOS)
        except Exception as e:
            errors.append(f"Preview failed for {png}: {e}")
            stats["errors"] += 1
            continue
        try:
            if img.mode not in ("RGB", "RGBA"):
                img = img.convert("RGBA")
            img.save(str(webp), "WEBP", quality=90)
        except Exception as e:
            errors.append(f"Preview failed for {png}: {e}")
            stats["errors"] += 1
            continue
        stats["rendered"] += 1
        print(f"  rendered {png.name} -> {webp.name}  ({img.width}x{img.height})")

    for sub in sorted(folder.iterdir(), key=lambda p: p.name.lower()):
        if sub.is_dir():
            render_folder(sub, size, force, stats, errors)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate WebP thumbnails for scene saves.")
    parser.add_argument("--saves", required=True, type=Path, help="Saves root directory")
    parser.add_argument("--size",  default="320x240",          help="Max thumbnail size WxH (default: 320x240)")
    parser.add_argument("--force", action="store_true",        help="Re-render even when the .webp is newer than the .png")
    args = parser.parse_args()

    saves = args.saves.resolve()
    if not saves.is_dir():
        sys.exit(f"ERROR: --saves not found: {saves}")

    size = parse_size(args.size)
    stats  = {"rendered": 0, "skipped": 0, "no_png": 0, "errors": 0}
    errors: list = []

    print(f"Saves: {saves}")
    print(f"Size:  {size[0]}x{size[1]}")
    print(f"Mode:  {'force' if args.force else 'incremental'}\n")

    render_folder(saves, size, args.force, stats, errors)

    print(f"\n{stats['rendered']} rendered, {stats['skipped']} skipped, "
          f"{stats['no_png']} without .png, {stats['errors']} error(s)")
    if errors:
        print("\nErrors:")
        for e in errors:
            print(f"  {e}")

    if errors:
        sys.exit(1)


if __name__ == "__main__":
    main()
